version: '3.9'

services:
  nginx:
    image: tutum/nginx
    ports:
      - "80:80"
    depends_on:
      - phpfpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
  phpfpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - ./public:/usr/share/nginx/html
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1